### ISSUE TITLE
Streaming PATCH updates are not reflected in client store

### ISSUE THREAD

**Issue by bjreath** [launchdarkly/ruby-client#76]
I'm running into the following scenario while upgrading to ldclient-rb 2.0.3 from ldclient-rb 0.7.0. The gem is used within a Rails 4.2.7.1 application on Puma.

The feature flags are working fine in our development environment when the application first loads, and it appears the correct values are returned initially. However, if a user goes to the LaunchDarkly web interface and toggles a flag, the update is not reflected within the Rails application until the Rails server is killed and restarted. This led me to believe we might be having an issue with handling `PATCH` server-sent event passed back from LaunchDarkly when the flag is changed.

In `config/initializers/launch_darkly.rb`:
```ruby
config = LaunchDarkly::Config.new(connect_timeout: 2, read_timeout: 2, offline: false)
Rails.configuration.features_client = LaunchDarkly::LDClient.new(ld_api_key, config)
```

We then use this global in our code to check for enabled features. As is the default, the `LaunchDarkly::StreamProcessor` is configured as the update processor within the client. I put some logging into this class to see if the `PATCH` SSEs are being received and handled, and it does appear that they are.

```ruby
message = JSON.parse(message.data, symbolize_names: true)
@config.logger.info("[LDClient] Before #{@store.get(message[:path][1..-1])}")
@store.upsert(message[:path][1..-1], message[:data])
@config.logger.info("[LDClient] After #{@store.get(message[:path][1..-1])}")
```

This correctly reflects a new version number for the flag and the proper `on` value in the message.

However, any time the global `LaunchDarkly::LDClient#variation` method is accessed on `Rails.configuration.features_client` for the flag, the variation code returns the initial version that was present when the LDClient was initialized [on this line](https://github.com/launchdarkly/ruby-client/blob/master/lib/ldclient-rb/ldclient.rb#L121), which causes us to hit the [condition here](https://github.com/launchdarkly/ruby-client/blob/master/lib/ldclient-rb/ldclient.rb#L140) that returns the default flag value. It seems the update to the store is not being picked up from the client (even though accessing the store directly from the StreamProcessor logging statements above seem to indicate that the store was updated properly).

I'm continuing to dig in to see if I can identify the issue, but any pointers would be appreciated.

**Comment by justinucd** [comment]
Hi Brian,

Do you mind creating this as a support ticket?  You can email your message to support@launchdarkly.com and it will automatically create a ticket.  I will start investigating this right away though.

Best,
Justin

**Comment by bjreath** [comment]
@justinucd Done. Let me know if I can help with any other info, or if you want to hop on a ScreenHero or Skype call.

**Comment by bjreath** [comment]
This was an issue with how we were establishing connections in a forked process environment (e.g. when using Spring or Puma). We are now reestablishing connections in Puma's `on_worker_boot` hook and Spring's `after_fork` hook and all is well.

**Comment by bjreath** [comment]
@justinucd So handling things the way I mentioned above works fine to get the streaming updates to work, but now I'm getting this issue whenever I do a `rails console` and then `exit` out of it:

![screen shot 2016-11-10 at 11 32 34 am](https://cloud.githubusercontent.com/assets/5208/20187341/7a315478-a739-11e6-8c61-cc59bafd2026.png)

The connection is being established, but for some reason it seems like Celluloid can't shut down its actors properly and my console hangs for a bit before exiting.

**Comment by bjreath** [comment]
Response from LaunchDarkly:

```
Hey Brian,

That's caused by a bug in Celluloid, which we use in our client:

https://github.com/krisleech/wisper-celluloid/issues/4

We've been waiting for the Celluloid team to release 0.18.0-- once they do that we'll be able to bump on our end and fix the issue. 
-- John Kodumal 
```

[Related Celluloid issue](https://github.com/celluloid/celluloid/issues/728) (active in the last 8 days).

**Comment by mattbradley** [comment]
@bjreath 
> We are now reestablishing connections in Puma's on_worker_boot hook and Spring's after_fork hook and all is well.

How are you reestablishing the LD connection? Are you just setting your global to a new instance of `LaunchDarkly::LDClient`?

I've tried that (creating an `LDClient` in an initializer then later in Puma's `on_worker_boot`), but it seems that the original LDClient sticks around receiving streaming events. This is evident from the duplicated log messages when the client receives PATCH updates:

```
[LDClient] Stream received patch message
[LDClient] Stream received patch message
```

I can solve the problem by removing the initializer, but then the client won't be available in rake tasks or `rails console` unless explicitly instantiated. So, I was wondering if you managed to solve this problem?

**Comment by Manfred** [comment]
I can verify that this problem exists in all (pre-)fork environments, in our case we've seen it in Pow.cx (Rack on Nodejs), Passenger in Apache, and Resque.

My solution was to wrap the LDClient instances in a [connection pool](https://github.com/mperham/connection_pool) because that solves the problem without having to configure an `after_fork` separately for every forking environment. The downside of this solution is that you have to configure your connection pool properly relative to the number of forks to make sure you don't start blocking on client checkouts.

**Comment by Manfred** [comment]
The downside of using after fork to recreate the client is that it adds a lot of launch time to the forked child on the first variation query.

I tried solving this by keeping the feature store around so I could take the initialization hit once in the parent fork. I tried passing it into the Config parameters when the client is re-created. This doesn't work because `StreamProcessor` always starts uninitialized regardless of the state of the feature store.

**Comment by dlau** [comment]
@Manfred -- is the startup on forked child initialization causing a slow down in your application's critical path or is it incurred at start up?

I've been investigating related celluloid issues regarding cleanly shutting down all running actors. Can someone running into these problems run their code with the following line of code set globally:

```rb
require "celluloid/current"
$CELLULOID_DEBUG = true
```

**Comment by Manfred** [comment]
>  is the startup on forked child initialization causing a slow down in your application's critical path or is it incurred at start up?

Currently we initialize the client on the first query so it depends. The problem with the application is that queries are done on the model level so they can be triggered in a web process, in background tasks (Sidekiq and legacy Resque jobs), or in one-off scripts which are triggered either by hand or through cron. We didn't want to force a query on process boot because some processes don't have to query at all.

The problem in our case has nothing to do with actors not shutting down properly as far as I can tell. Sharing IO handles between forks is simply not possible so the current architecture of the gem will never work very well in forked environments. You will have to create an LDClient instance for every forked process.

I think the best solution for this problem depends on the size of the application. For smaller applications dealing with just a few RPM it makes more sense to have easy setup that works similar to the current code. For larger deployments it makes much more sense to have just one process in the architecture take care of synchronization to a local cache and then have all the web, background, and script processes read from that local cache.

**Comment by dlau** [comment]
@Manfred 

In your larger deployments, would something like a redis backed feature store solve your needs? Think a ruby corollary to the [java-client RedisFeatureStore](http://launchdarkly.github.io/java-client/com/launchdarkly/client/RedisFeatureStore.html)

Further, have you taken a look at [redis storage and daemon mode](https://github.com/launchdarkly/ld-relay#redis-storage-and-daemon-mode) in ld-relay?

**Comment by Manfred** [comment]
@dlau No, I haven't looked at other solutions because I was mostly working on upgrading the gem in the project. We haven't prioritized working on a more optimal integration with LD.

Using a Redis backed feature query interface with a separate update process was exactly what I was thinking about.
